### ISSUE TITLE
More than just JS scripts?

### ISSUE THREAD

**Issue by mathvav** [addyosmani/basket.js#123]
How hard would it be to extend the support beyond Javascript to other objects like CSS files or even assets like images or audio?

For the CSS it doesn't seem that hard to implement: you just add that as a stylesheet to the header instead of executing the code. Pictures and such may be a little more of a problem because they need to be added inline, not just in random places.

**Comment by addyosmani** [comment]
We've had this request quite a lot in the past. In general, the approach we have taken is trying to allow basket.js to be extensible so that such layers for handling CSS and other resource types could be added without too much pain. Take a look here for some examples of extensions being used for similar purposes: https://github.com/addyosmani/basket.js#examples
