### ISSUE TITLE
Missing files in bower

### ISSUE THREAD

**Issue by ffflabs** [addyosmani/basket.js#137]
For some reason, after installing with

``` sh
bower install --save basket.js
```

I'm missing every version of the script except for `basket.js`

![missing_basket](https://cloud.githubusercontent.com/assets/238439/6998931/670a5e00-dbc8-11e4-98e5-4f02f7d0f0bb.png)

Of course, I can manually download basket.min.js and basket.full.min.js, but I'll lose them once I update bower dependencies.

BTW, what's the difference on the full version vs the normal version? Does it include RSVP?

**Comment by MarkusPint** [comment]
+1 I need to use basket.full.js, which includes only the essential parts of RSVP.

**Comment by PatrickWalker** [comment]
https://github.com/bower/bower/issues/368 indicates this is by design and that the proposed options are
1) *Preferred* - You handle the minification in the consuming project with your own resources and I guess the goal here is you have flexibility to do that how you want
2) A new minified version of the package is made available a basket-full.js or basket-min.js as applicable.
3) The pattern used by RSVP is followed here and the minified files are added in. This appears to be 'against' the intent of bower but is clearly possible as RSVP have managed it

I think that for 1 and 2 (and I might be massively wrong here) the map files don't offer much value without the minified JS so I think it would make sense to exclude them from the bower package

**Comment by PatrickWalker** [comment]
Sorry ignore me. There has been a change put in for this
https://github.com/addyosmani/basket.js/commits/gh-pages/bower.json
this isn't part of the latest release as there hasn't been one since Feb 2015
