### ISSUE TITLE
Support file-versioning (new option: version)

### ISSUE THREAD

**Issue by peol** [addyosmani/basket.js#26]
It would be great if we could force update of a specific key automatically by specifying the version:

```
basket.add('foo.min.js', { key: 'foo', version: '1.0' });

// would do nothing since we already stored foo
basket.add('foo.min.js', { key: 'foo' });

// we updated the version, let's update localStorage as well
basket.add('foo.min.js', { key: 'foo', version: '1.1' });
```

Is this overkill? It's somewhat like `overwrite`, but we'll only do it once the version is updated.

**Comment by sindresorhus** [comment]
Since I suggested it, I should probably write why:

The thought is that the version is like a checksum, we don't care about the format or anything about it, only if it's changed or not. When a the version is changed, it will remove the old one, and add in this (like overwrite). This is similar to overwrite, but with one big difference, I don't have to think about the last version used. With overwrite, you need to remember if you have to overwrite, this can cause subtle bugs when forgotten. A better name for it would probably be something like `id` or `hash`. I think this can actually replace overwrite, since you can just change the version to get the same effect.

@addyosmani Thoughts?

**Comment by addyosmani** [comment]
(please forgive the brevity as I'm mobile)

Michael Mahemoff suggested that we opt for a checksum/hash approach a while back for versioning, but I think your expanded notes and justification make a lot of sense Sindre. My view is that there's no reason we shouldn't be doing the below. You're bang on right about not caring about the overwrite but wouldn't we need to redownload a script that is already cached just to compare hash/checksums?

**Comment by sindresorhus** [comment]
We would only need to download the script that .requires the dependencies, but this is wanted, since it gets updated.

``` javascript
basket.require({
    url: 'http://website.com/foo.js',
    key: 'foo.js',
    hash: '123'
});
```

It would then be replaced if we changed the hash:

``` javascript
basket.require({
    url: 'http://website.com/foo.js',
    key: 'foo.js',
    hash: '321'
});
```

**Comment by peol** [comment]
So, basically, `hash` just acts as the classic `?_=<random number>` cache bust. I guess that makes sense, but perhaps it should be named something more in line with what it actually does?

```
basket.require({
    url: 'http://website.com/foo.js',
    key: 'foo.js',
    unique: '321'
});
```

?

**Comment by sindresorhus** [comment]
Yes, exactly ;) Hash is descriptive enough for me, but other might not get that. `unique` could work too.

**Comment by mahemoff** [comment]
It was proposed in #2 like this:

```
.require('jquery-1.7.2.js, {key: 'jquery'})
```

The thinking being that you change the URL whenever you want to change the resource.

If you really want to take this approach, you could leverage the existing ETag standard, i.e. check the response header for an ETag, store it, and pass it back to the server upon next request. But I think it's overkill for the current scope of basket, in which the client and server are likely controlled and trusted by the same party. Since that's the case, just rev the version in the URL.

**Comment by sindresorhus** [comment]
@mahemoff Yes, I've seen the proposal, and I really like the checksum idea, but as you said yourself, a little too much.

> The thinking being that you change the URL whenever you want to change the resource.

That's a valid thinking, but I (and probably a lot of other devs) mostly use a static filename for my JS files `main.js`, `jquery.min.js`, etc. You could of course append an url parameter, but then the hash/unique property is a lot cleaner.

**Comment by mahemoff** [comment]
Fair enough, it's really a question for Addy to decide then, depending on
his views and how opinionated the library is.

I wouldn't particularly mind this option as long as I could happily ignore
it if I committed to keep URLs unique for different script versions.

**Comment by addyosmani** [comment]
Appreciate the input, @mahemoff!

To be honest, I've seen both approaches taken with similar levels of success. I'm completely open to us reconsidering the direction taken with hash/uniques, but what we'll probably do is wait until we've heard what the feedback is from users on the approached using hash/unique. At the end of the day, I want us to balance least effort (on a user's part) with flexibility.

**Comment by sindresorhus** [comment]
I would have no problem in supporting both btw, but what Addy said ^
