### ISSUE TITLE
Project future

### ISSUE THREAD

**Issue by addyosmani** [addyosmani/basket.js#36]
@peol @sindresorhus 

When we originally started this project we wanted to see if we could create a useful POC that people could use for script caching. LocalStorage support has improved since then. Do you think we should continue to maintain / update in the next few months with TTL support and so on or sunset the project?

(sunsetting in this case would just update the readme to state its no longer maintained)

**Comment by sindresorhus** [comment]
I've been wanting to do that for some time, but I never seem to get the time to do it :/

I don't think we should sunset it yet, let's give it a few more months.

**Comment by peol** [comment]
Agree, we're somewhat playing around with this at work the coming weeks/months or so, I still feel that there's a place for a lib like this, and nothing else that I've seen looks as versatile as this project.

**Comment by addyosmani** [comment]
Sounds good to me. Let's revisit in Jan/Feb and see if there's interest in a new version with more features. Cheers guys!

**Comment by TomiS** [comment]
Hi guys!

Might I give you some suggestions for the future...

Let me first explain my situation for background info. I'm trying to develop a mobile hybrid application with Apache Cordova at the moment and I'm keeping some of my library javascripts (Backbone, jQuery, etc) in local folder and some application specific files (models, views) I'm loading from the web because I wan't to be able to develop them without going through the hard app store deployment processes for every supported platform all the time.

Currently I'm also using require.js to load those files and it means I need to make close to 20 http request every time I start the application just to get those models and views. What I'd like to do, is to store those models ans views locally (in localStorage) to be able to avoid unnecessary http requests when I know views and models have not been changed. Also, I'd like my app to start even without web connection and that is a problem for pure require.js too.

So I'm asking, since asynchronous module loading (and require.js) seem to be quite a hot topic nowadays, have you considered some kind of integration of basket.js with require.js. Could basket.js become a plugin for require.js or something?

Br, Tomi

**Comment by peol** [comment]
That's an interesting idea but I think that's a classical example of what an extension/wrapper could do. basket.js could probably very easily become a mediator between require.js and actual XHR calls, so I think it's definitely doable but more something that are outside the scope of this project.

**Comment by addyosmani** [comment]
+1 to the above. There is however an AMD loader that loads from localstorage  (also Web SQL, IndexedDB and FileSystem API via a configured storage  implementation) in case that helps https://github.com/zazl/lsjs

**Comment by TomiS** [comment]
@peol Ok, I see

@addyosmani Thanks for the tip. I'm definitely gonna check that out too.
