### ISSUE TITLE
Require queue method

### ISSUE THREAD

**Issue by felipemorais** [addyosmani/basket.js#52]
I'd like to add a require queue method. ( i.e. A file could be fetched only after previous file ).

```
basket.requireQueue({url:'jquery.js'}, {url:'jquery.plugin.js'}).then...
```

It make sense for most of my use cases. 
Instead:

```
basket
  .require({url:'jquery.js'})
  .then(function(){
    basket
      .require({url:'jquery.plugin.js'}, {url:'jquery.effects.js'})
      .then(function(){
        basket.require({url:'mycode.js'});
    });
  });
```

Make sense?

**Comment by peol** [comment]
Maybe an `async` option?

`basket.require({ url: 'jquery.js', async: false }, { url: 'jq-plugin.js'
}).then(fn)`.

**Comment by addyosmani** [comment]
An async option would be nice :)

**Comment by addyosmani** [comment]
@felipemorais did you have any interest in exploring adding an implementation of this to basket?

**Comment by wibblymat** [comment]
I've been thinking that for convenience we could mixin a method into the promise returned by require with something like:

``` javascript
function require(options...) {
  // blah, blah, current require body
  promise.thenRequire = this.thenRequire;
  return promise;
}

function thenRequire(options...) {
  var promise = this.then(function() {
    basket.require(options...);
  });
  promise.thenRequire = this.thenRequire;
  return promise;
}
```

but I'm not sure if that feels icky somehow.

``` javascript
basket.require({url: 'jquery.js'})
  .thenRequire({url: 'backbone.js'})
  .thenRequire({url: 'main.js'})
  .then(entryPoint, errorHandler); 
```

**Comment by wibblymat** [comment]
Something like 280a0da643cfbcf586e3a977a56ec6b81f94f0e8

**Comment by felipemorais** [comment]
thenRequire sgtm.

**Comment by addyosmani** [comment]
Correct me if I'm wrong, is this similar to the LAB.js wait() method? http://labjs.com/documentation.php. If so, using that signature might look like:

``` js
basket.require({url: 'jquery.js'}).wait()
  .require({url: 'backbone.js'})
  .require({url: 'main.js'})
  .then(entryPoint, errorHandler); 
```

Would that be cleaner? Again, sorry if I've misunderstood what you're doing.

**Comment by wibblymat** [comment]
The wait() method there is also like the old basket.js wait() or the new then() in that it accepts a callback.

Because in the LABjs style interface you can do require().require(), require().wait() and require().then(), the require method would still have to return a promise with the extra methods added. And the require() method on the promise would need to be basically the same as the thenRequire method we already have, I think.

Hmm, actually the LABjs thing is slightly different. With thenRequire, as it stands, the later scripts don't even download until the first require is completed. With LABjs it begins fetching all scripts immediately, but _executes_ them in the given order. That could make your page loads a fair bit faster.

So, IMO, the thenRequire interface is tidier and easier to implement for the same end, but starting the fetch early is a very good feature we should borrow. Renaming thenRequire to just be require might make the interface feel simpler, too.

Something like

``` javascript
basket.require({url "jquery.js" }, {url: "backbone.js" })
    .require({ url: "jquery-ui.js" });
```

would download all three scripts in parallel, but jquery-ui would not be executed until jquery and backbone had been.

**Comment by addyosmani** [comment]
Ah! That makes sense now. Thanks for clarifying @wibblymat. With that in mind, `thenRequire` lgtm too!
