### ISSUE TITLE
Discussion of plugins for new resource types

### ISSUE THREAD

**Issue by wibblymat** [addyosmani/basket.js#77]
I created [a gist](https://gist.github.com/wibblymat/4754410) with some thoughts on the subject based on @addyosmani's question at https://github.com/addyosmani/basket.js/pull/76#issuecomment-13333077.

Discuss!

@peol @sindresorhus

**Comment by wibblymat** [comment]
@addyosmani from the timing of the comment that triggered this I'm guessing that you posted it shortly after the Offline session at Edge conf. Was there something interesting/relevant that came up in the discussion afterwards that prompted it?

[The video of the session](http://www.youtube.com/watch?v=Oic22dQMRXQ&feature=share&list=SPNYkxOF6rcICCU_UD67Ga0qLvMjnBBwft) was interesting for anyone who hasn't seen it, btw.

**Comment by sindresorhus** [comment]
I agree with this proposal. Binary data is not suitable for localStorage, so only text sounds good to me.

**Comment by addyosmani** [comment]
Edge confirmed that whilst there are alternative mechanisms for caching data offline, developers should continue using what works best for them as long as they benchmark it.

We have a thread going on internally about how effective solutions like basket are in practice but agreement that browser cache, appcache and local storage would benefit from improvements.

I also liked your proposal :)

**Comment by addyosmani** [comment]
I feel like basket.js is used as a reference implementation rather than directly as an include by many people. If that's the case, I actually would love for us to include plugins for it that solve caching different resource types so that the community have examples for solving that problem. Perhaps after things have calmed down with Bower we could re-explore this.
